version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - node-api
      - auth-api
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  node-api:
    image: node:18
    working_dir: /app
    volumes:
      - ./node-api:/app
    command: >
      sh -c "npm install --no-audit --no-fund && node index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-api:
    image: node:18
    working_dir: /app
    volumes:
      - ./auth-api:/app
    command: >
      sh -c "npm install --no-audit --no-fund && node index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  postman-tests:
    build: ./postman
    volumes:
      - ./postman:/tests
    depends_on:
      nginx:
        condition: service_healthy
      node-api:
        condition: service_healthy
      auth-api:
        condition: service_healthy
    environment:
      - NEWMAN_DISABLE_SSL_VERIFICATION=1
    profiles:
      - test
