version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - node-api
      - auth-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:80/api/public"]
      interval: 10s
      timeout: 5s
      retries: 3

  node-api:
    image: node:18
    working_dir: /app
    volumes:
      - ./node-api:/app
    command: >
      sh -c "npm install --no-audit --no-fund && node index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://node-api:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-api:
    image: node:18
    working_dir: /app
    volumes:
      - ./auth-api:/app
    command: >
      sh -c "npm install --no-audit --no-fund && node index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-api:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
